
title: the Inspired Ones
description: >-
  the Inspired Ones war eine kleine Agentur für Webdesign und -entwicklung aus NRW.
url: "https://the-inspired-ones.de"
permalink: /:title
timezone: Europe/Berlin
sass:
  style: compressed
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - CNAME
gems:
  - jekyll-email-protect
