
title: the Inspired Ones
description: >-
  The Inspired Ones ist eine kleine Agentur für Webdesign und -entwicklung aus NRW. Mit viel Liebe zum Detail bieten wir Ihnen beste Voraussetzungen für ihren kleinen bis mittelgroßen Webauftritt.
url: "https://the-inspired-ones.de"
permalink: /:title
timezone: Europe/Berlin
sass:
  style: compressed
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - CNAME
gems:
  - jekyll-email-protect
